// components/Sections/About.vue
<template>
  <section class="flex flex-col justify-center items-center relative" id="about">
    <div class="container" id="about-me">
      <div class="about-desc">
        <h4 class="uppercase">Yeris Aguilar</h4>
        <p class="my-3">{{ $t('aboutMeText') }}</p>

        <div class="relative ">
          <a href="" class="btn-purple mt-3">{{ $t('downloadTextBtn') }}</a>
        </div>
      </div>
      <div class="image-container flex justify-center relative ">
        <div class="image relative pt-6 pl-8">
          <img src="/assets/img.png" class="rounded-lg relative z-0" alt="yeris image" />
        </div>
      </div>
    </div>
    <!-- skills -->
    <div class="flex justify-between w-full px-40 py-10">
      <div class="text-center">
        <img src="/assets/wp.svg" class="w-30 h-30" alt="wordpress icon">
        <p class="mt-3 text-[#adaeaf]">WordPress</p>
      </div>
      <div class="text-center">
        <img src="/assets/bitbucket.svg" class="w-30 h-30" alt="Bitbucket icon">
        <p class="mt-3 text-[#adaeaf]">Bitbucket</p>
      </div>
      <div class="text-center">
        <img src="/assets/vue.svg" class="w-30 h-30" alt="vue icon">
        <p class="mt-3 text-[#adaeaf]">Vue.js</p>
      </div>
      <div class="text-center">
        <img src="/assets/css.svg" class="w-30 h-30" alt="css icon">
        <p class="mt-3 text-[#adaeaf]">CSS</p>
      </div>
      <div class="text-center">
        <img src="/assets/boostrap.svg" class="w-30 h-30" alt="bootstrap icon">
        <p class="mt-3 text-[#adaeaf]">Bootstrap</p>
      </div>
      <div class="text-center">
        <img src="/assets/git.svg" class="w-30 h-30" alt="git icon">
        <p class="mt-3 text-[#adaeaf]">Git</p>
      </div>
      <div class="text-center">
        <img src="/assets/github_.svg" class="w-30 h-30" alt="wordpress icon">
        <p class="mt-3 text-[#adaeaf]">WordPress</p>
      </div>
    </div>
    <!-- <div class="container">
          <div class="tech-slider"></div>
          <div class="skill-slider"></div>
        </div> -->
    <div class="w-10/12 flex justify-center">
      <Carousel />
    </div>
  </section>
</template>

// app/components/about.jsx
import image from "~/assets/img.png";
import Skills from "./skills";
import Tech from "./tech";
const About = () => {
  return (
    <div id="about" className="">
      <div className="container ">
        <div className="row justify-content-between">
          <div className="col-5 img-cont text-end">
              <img src={image} alt="dev" className="img-fluid"/>
           
          </div>
          <div className="col-6">
            <div className="about-me">
              <h2>Yeris AlejanDRa Aguilar</h2>
              <p>
                I skillfully navigated a diverse technology stack, including
                HTML, CSS, SASS, Bootstrap, JavaScript, and jQuery. I
                demonstrated proficiency in version control using Git, with a
                particular focus on platforms like GitHub and Bitbucket. I
                seamlessly integrated Restful APIs, enhancing the functionality
                and scope of projects. Furthermore, I contributed to WordPress
                theme development, employing tools like ACF to create robust and
                tailored solutions. My expertise also extended to React.js,
                where I crafted dynamic and engaging web experiences.
              </p>
              <div className="d-flex download-container">
                <a href="#" className="btn download">
                  Download My CV
                </a>
                <div className="download-btn"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex container">
        {/* slider */}
        <Tech />
      </div>
      <div className="container">
        <Skills />
      </div>
    </div>
  );
};

export default About;
