// components/Sections/Hero.vue
<template>
  <section class="flex flex-col w-full text-white justify-center items-center relative" id="hero">
    <div class="xl:w-4/12 text-center">
      <h6 class="uppercase"><span>Yeris Aguilar -</span> front end</h6>
      <h1 class="uppercase mb-3">
        Web <br class="display" />
        developer
      </h1>
      <p>
       {{ $t("heroDescription") }}
      </p>
      <div class="btn-container mt-5">
        <a href="#contact" class="btn">{{ $t('contactText') }}</a>
      </div>
    </div>
  </section>
</template>

// app/components/hero.jsx
import { Link } from "@remix-run/react";

const Hero = () => {
  return (
    <div id="hero" className="">
      <div className="container text-center ">
        <div className="col-10 m-auto">
            
        <h3>Yeris Alejandra Aguilar - FRONT END </h3>
        <h1>WEB DEVELOPER</h1>
        <p>
          Hello! I'm Yeris, a passionate front-end web developer with a knack
          for crafting captivating online experiences. <span>Contact me today</span>, and
          let's create something extraordinary together.
        </p>
        <div className="flex justify-center align-center contact-container">
          <Link to="#contact" className="btn contact">
            Contact
          </Link>
          <p className="click-here">Click Here</p>
        </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;
